name: Trigger auto deployment for container-app-glniidlmqtgng

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-glniidlmqtgng-AutoDeployTrigger-7677489b-a9ee-4c9c-9638-5c0aa31f3345.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGLNIIDLMQTGNG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGLNIIDLMQTGNG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGLNIIDLMQTGNG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPGLNIIDLMQTGNG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGLNIIDLMQTGNG_REGISTRY_PASSWORD }}
          containerAppName: container-app-glniidlmqtgng
          resourceGroup: flowise98e6
          imageToBuild: default/container-app-glniidlmqtgng:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


